apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-1
  namespace: default
spec:
  replicas: 5
  selector:
    matchLabels:
      app: project-1-app
  template:
    metadata:
      labels:
        app: project-1-app
    spec:
      containers:
        - name: project-1
          image: kasbesruthi/project-1:build-5
          ports:
            - containerPort: 5000